In [1]:
from pathlib import Path

raw_dir = Path("../data/raw")

for file in raw_dir.iterdir():
    print(file)

..\data\raw\large_sample.csv

In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/large_sample.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [18]:
df.shape

(300000, 8)

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300000 entries, 0 to 299999
Data columns (total 8 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   tweet_id                 300000 non-null  int64
 1   author_id                300000 non-null  str
 2   inbound                  300000 non-null  bool
 3   created_at               300000 non-null  str
 4   text                     300000 non-null  str
 5   response_tweet_id        49560 non-null   float64
 6   in_response_to_tweet_id  40332 non-null   float64
 7   text_length              300000 non-null  int64
dtypes: bool(1), float64(2), int64(2), str(3)
memory usage: 16.3 MB

In [7]:
df.isnull().sum()

tweet_id                        0
author_id                       0
inbound                         0
created_at                      0
text                            0
response_tweet_id          250440
in_response_to_tweet_id    259668
dtype: int64

In [12]:
df["text_length"] = df["text"].astype(str).str.len()

df["text_length"].describe()

count    300000.000000
mean         76.735143
std          12.853187
min          52.000000
25%          65.000000
50%          75.000000
75%          87.000000
max         109.000000
Name: text_length, dtype: float64

In [14]:
pd.set_option("display.max_colwidth", 300000)

df[["text"]].sample(20, random_state=42)

                                                                                                              text
4941                       @@555557 Thanks for letting us know. Please send us a DM so we can investigate further.
51775                                            @Uber_Support I've tried several times but it still doesn't work.
115253        @@892757 We're sorry you're experiencing this. Please send us a DM with more details and we'll help.
299321                                   @ChaseSupport please help me resolve this issue as soon as possible. ASAP
173570                                        @British_Airways can you explain what happened and how I can fix it?
30862                      @@308822 Thanks for letting us know. Please send us a DM so we can investigate further.
244471               @@658875 Thanks for reaching out. Please DM us your details so we can look into this for you.
127794                                     @ChaseSupport this isn't working as expected. Can someone look into it?
71558                                                  @SpotifyCares I've been waiting for a response. Any update?
218011            @SouthwestAir I've tried several times but it still doesn't work. I've already tried restarting.
148208                     @@508063 Thanks for letting us know. Please send us a DM so we can investigate further.
155735                        @@509152 We understand your concern. Please DM us the details and we'll take a look.
100698                                      @ATVIAssist this problem keeps happening and it's getting frustrating.
241403        @@945993 We're sorry you're experiencing this. Please send us a DM with more details and we'll help.
195272  @Uber_Support this problem keeps happening and it's getting frustrating. This has been happening for days.
238663                     @@674943 Thanks for letting us know. Please send us a DM so we can investigate further.
262957               @@247603 Thanks for reaching out. Please DM us your details so we can look into this for you.
207082        @@207383 We're sorry you're experiencing this. Please send us a DM with more details and we'll help.
298896                     @@394566 Thanks for letting us know. Please send us a DM so we can investigate further.
220946                                            @VirginTrains I'm having trouble with my account. Please advise.

In [17]:
customer_df = df[df["inbound"] == True]

customer_df[["text"]].sample(
    30,
    random_state=42
)

                                                                               text
98874               @sprintcare can you explain what happened and how I can fix it?
30559               @AppleSupport my issue is still not fixed. Can you please help?
205913                @VerizonSupport why is this happening? I need help with this.
107477                         @Delta I've been waiting for a response. Any update?
293937           @ATVIAssist please help me resolve this issue as soon as possible.
190638          @British_Airways I'm having trouble with my account. Please advise.
224208                  @AppleSupport why is this happening? I need help with this.
84654    @British_Airways this isn't working as expected. Can someone look into it?
19816             @SpotifyCares I've tried several times but it still doesn't work.
73784             @ChaseSupport I've tried several times but it still doesn't work.
39486             @AskPlayStation my issue is still not fixed. Can you please help?
241914            @Delta I need help with my payment/account/order. Please respond.
145408   @sprintcare this isn't working as expected. Can someone look into it? ASAP
63005              @ChaseSupport I'm having trouble with my account. Please advise.
121636            @Delta I need help with my payment/account/order. Please respond.
188721            @Delta I need help with my payment/account/order. Please respond.
90876          @AmazonHelp I've tried several times but it still doesn't work. ASAP
116942            @ChaseSupport my issue is still not fixed. Can you please help? 😕
199359          @AskPlayStation can you explain what happened and how I can fix it?
265107             @AppleSupport I'm having trouble with my account. Please advise.
242793            @VirginTrains I've tried several times but it still doesn't work.
93840                    @AmericanAir why is this happening? I need help with this.
203252             @Uber_Support I'm having trouble with my account. Please advise.
213271       @Uber_Support can you explain what happened and how I can fix it? ASAP
9002                  @sprintcare my issue is still not fixed. Can you please help?
28394                   @Ask_Spectrum I've been waiting for a response. Any update?
190161               @sprintcare I'm having trouble with my account. Please advise.
261859  @British_Airways I need help with my payment/account/order. Please respond.
256848   @British_Airways this isn't working as expected. Can someone look into it?
84373           @AmericanAir please help me resolve this issue as soon as possible.

In [22]:
df["author_id"].value_counts().head(30)

author_id
British_Airways    8560
SpotifyCares       8535
VirginTrains       8510
Delta              8504
AmazonHelp         8495
AmericanAir        8484
Ask_Spectrum       8466
sprintcare         8438
SouthwestAir       8424
XboxSupport        8384
ATVIAssist         8378
AppleSupport       8369
VerizonSupport     8307
ChaseSupport       8304
Uber_Support       8253
AskPlayStation     8196
780508                5
750363                4
157630                4
447409                4
517645                4
267870                4
147678                4
100353                4
440906                4
648822                4
372557                4
187582                4
413692                4
657178                4
Name: count, dtype: int64

In [23]:
df["inbound"].value_counts()

inbound
True     165393
False    134607
Name: count, dtype: int64

In [24]:
customer_tweets = df[df["inbound"] == True]
support_tweets = df[df["inbound"] == False]

In [25]:
support_tweets["author_id"].value_counts().head(20)

author_id
British_Airways    8560
SpotifyCares       8535
VirginTrains       8510
Delta              8504
AmazonHelp         8495
AmericanAir        8484
Ask_Spectrum       8466
sprintcare         8438
SouthwestAir       8424
XboxSupport        8384
ATVIAssist         8378
AppleSupport       8369
VerizonSupport     8307
ChaseSupport       8304
Uber_Support       8253
AskPlayStation     8196
Name: count, dtype: int64

BRANDS WITH MOST TWEETS

In [26]:
candidate_brands = (
    support_tweets["author_id"]
    .value_counts()
    .head(10)
)

candidate_brands

author_id
British_Airways    8560
SpotifyCares       8535
VirginTrains       8510
Delta              8504
AmazonHelp         8495
AmericanAir        8484
Ask_Spectrum       8466
sprintcare         8438
SouthwestAir       8424
XboxSupport        8384
Name: count, dtype: int64

In [27]:
brands = candidate_brands.index.tolist()

brand_stats = []

for brand in brands:
    brand_support = df[
        (df["author_id"] == brand) &
        (df["inbound"] == False)
    ]

    brand_stats.append({
        "brand": brand,
        "support_tweets": len(brand_support)
    })

brand_stats = pd.DataFrame(brand_stats)

brand_stats

             brand  support_tweets
0  British_Airways            8560
1     SpotifyCares            8535
2     VirginTrains            8510
3            Delta            8504
4       AmazonHelp            8495
5      AmericanAir            8484
6     Ask_Spectrum            8466
7       sprintcare            8438
8     SouthwestAir            8424
9      XboxSupport            8384

In [28]:
df[
    ["tweet_id",
     "author_id",
     "inbound",
     "text",
     "response_tweet_id",
     "in_response_to_tweet_id"]
].head(20)

,tweet_id,author_id,inbound,text,response_tweet_id,in_response_to_tweet_id
0,119336,VirginTrains,False,@@333814 Sorry for the trouble. Please send us a DM with the requested information.,NaN,NaN
1,119337,British_Airways,False,@@468144 Thanks for reaching out. Please DM us your details so we can look into this for you.,NaN,NaN
2,119338,352187,True,@VirginTrains my issue is still not fixed. Can you please help?,NaN,NaN
3,119339,AppleSupport,False,@@531134 Sorry for the trouble. Please send us a DM with the requested information.,NaN,NaN
4,119340,Ask_Spectrum,False,@@915541 We'd be happy to help. Please DM us the relevant account/order details.,NaN,NaN
5,119341,743873,True,@British_Airways this isn't working as expected. Can someone look into it?,NaN,NaN
6,119342,647721,True,@Delta this isn't working as expected. Can someone look into it?,NaN,NaN
7,119343,356294,True,@ATVIAssist why is this happening? I need help with this.,NaN,NaN
8,119344,610254,True,@AmazonHelp I'm having trouble with my account. Please advise.,NaN,NaN
9,119345,129788,True,@ChaseSupport please help me resolve this issue as soon as possible.,NaN,NaN
10,119346,sprintcare,False,@@557186 Thanks for reaching out. Please DM us your details so we can look into this for you.,NaN,158444.0
11,119347,Uber_Support,False,@@118128 We understand your concern. Please DM us the details and we'll take a look.,NaN,NaN
12,119348,199149,True,@British_Airways this problem keeps happening and it's getting frustrating.,NaN,NaN
13,119349,520864,True,@ChaseSupport my issue is still not fixed. Can you please help?,NaN,NaN
14,119350,284889,True,@SouthwestAir my issue is still not fixed. Can you please help? 😕,NaN,NaN
15,119351,121793,True,@VerizonSupport this isn't working as expected. Can someone look into it?,242728.0,NaN
16,119352,713002,True,@ChaseSupport this isn't working as expected. Can someone look into it?,NaN,NaN
17,119353,sprintcare,False,@@306875 We understand your concern. Please DM us the details and we'll take a look.,NaN,NaN
18,119354,578366,True,@AskPlayStation I've tried several times but it still doesn't work.,NaN,NaN
19,119355,AmericanAir,False,@@622285 Thanks for reaching out. Please DM us your details so we can look into this for you.,NaN,NaN

In [29]:
df["conversation_id"] = df["in_response_to_tweet_id"].fillna(df["tweet_id"])

In [30]:
df[
    ["tweet_id", "in_response_to_tweet_id", "conversation_id", "text"]
].head(20)

,tweet_id,in_response_to_tweet_id,conversation_id,text
0,119336,NaN,119336.0,@@333814 Sorry for the trouble. Please send us a DM with the requested information.
1,119337,NaN,119337.0,@@468144 Thanks for reaching out. Please DM us your details so we can look into this for you.
2,119338,NaN,119338.0,@VirginTrains my issue is still not fixed. Can you please help?
3,119339,NaN,119339.0,@@531134 Sorry for the trouble. Please send us a DM with the requested information.
4,119340,NaN,119340.0,@@915541 We'd be happy to help. Please DM us the relevant account/order details.
5,119341,NaN,119341.0,@British_Airways this isn't working as expected. Can someone look into it?
6,119342,NaN,119342.0,@Delta this isn't working as expected. Can someone look into it?
7,119343,NaN,119343.0,@ATVIAssist why is this happening? I need help with this.
8,119344,NaN,119344.0,@AmazonHelp I'm having trouble with my account. Please advise.
9,119345,NaN,119345.0,@ChaseSupport please help me resolve this issue as soon as possible.
10,119346,158444.0,158444.0,@@557186 Thanks for reaching out. Please DM us your details so we can look into this for you.
11,119347,NaN,119347.0,@@118128 We understand your concern. Please DM us the details and we'll take a look.
12,119348,NaN,119348.0,@British_Airways this problem keeps happening and it's getting frustrating.
13,119349,NaN,119349.0,@ChaseSupport my issue is still not fixed. Can you please help?
14,119350,NaN,119350.0,@SouthwestAir my issue is still not fixed. Can you please help? 😕
15,119351,NaN,119351.0,@VerizonSupport this isn't working as expected. Can someone look into it?
16,119352,NaN,119352.0,@ChaseSupport this isn't working as expected. Can someone look into it?
17,119353,NaN,119353.0,@@306875 We understand your concern. Please DM us the details and we'll take a look.
18,119354,NaN,119354.0,@AskPlayStation I've tried several times but it still doesn't work.
19,119355,NaN,119355.0,@@622285 Thanks for reaching out. Please DM us your details so we can look into this for you.

In [31]:
conversation_lengths = (
    df.groupby("conversation_id")
      .size()
)

conversation_lengths.describe()

count    264750.000000
mean          1.133144
std           0.364728
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           5.000000
dtype: float64